import AboutSection from "@/components/AboutSection/AboutSection"
import CategoryCards from "@/components/CategoryCards/CategoryCards"

export const metadata = {
  title: "Audiophile e-commerce website",
  description: "Generated by create next app",
}

export default function CategoryLayout({ children }) {
  return (
    <div>
      {children}
      <CategoryCards />
      <AboutSection />
    </div>
  )
}
